### ISSUE TITLE
Timestamps do not account for time zone

### ISSUE THREAD

**Issue by Bodigrim** [NorfairKing/feedback#10]
https://github.com/NorfairKing/feedback/blob/3928be61d28d480d043eb01394c8e55478ab969e/feedback/src/Feedback/Common/Output.hs#L20-L23

I've been a bit confused by timestamps, referring far in the past. The thing is that `getCurrentTime` returns `UTCTime` and does not account for local time zone. I'm not sure, but maybe `getZonedTime` is a better default?

**Comment by NorfairKing** [comment]
Oh, duh! That's a silly mistake :p

**Comment by NorfairKing** [comment]
Quickly fixed!

**Comment by Bodigrim** [comment]
Thanks!
