### ISSUE TITLE
Is Windows supported?

### ISSUE THREAD

**Issue by Bodigrim** [NorfairKing/feedback#5]
I can build `feedback.exe`, but it does not seem to be functional: `feedback --help` just freezes.

**Comment by NorfairKing** [comment]
Hi @Bodigrim 
I haven't used windows in ten years so I won't be able to provide windows support.
But the codebase is small, so if you would like to maintain windows support then I'd be happy to have you onboard.

**Comment by Bodigrim** [comment]
I use Windows in the office, but sadly do not posess much expertise with Windows-specific issues :( I'll document my ramblings below, maybe someone else will be able to help.

The first hurdle is to build `terminfo`, which presumably requires an MSYS package similar to `ncurses-dev`. This does not seem to be documented upstream, I raised https://github.com/judah/terminfo/issues/46, because none of my efforts to download necessary headers via `pacman` were successful. I ended up replacing `safe-coloured-text-terminfo` dependency with a stub, after which I was able to build `feedback.exe`, but even `feedback --help` freezes. I might very well messed up with a stub for `safe-coloured-text-terminfo`, but do not have access to the code at the moment. 

@NorfairKing how do you feel about making `safe-coloured-text-terminfo` an optional dependency, so that systems which have difficulties with `terminfo` could use `feedback` in monochrome mode?

(`feedback` coloured output is gourgeous!)

**Comment by NorfairKing** [comment]
> @NorfairKing how do you feel about making safe-coloured-text-terminfo an optional dependency, so that systems which have difficulties with terminfo could use feedback in monochrome mode?

That sounds entirely acceptable. [Sydtest already does something like this](https://github.com/NorfairKing/sydtest/blob/e55fad0f6b8058a9b44c6c0d66bdd3c3be556d71/sydtest/package.yaml#L91-L94) and it's I we made `safe-coloured-text-terminfo` a separate package. :D

**Comment by Bodigrim** [comment]
The next hurdle is 
https://github.com/NorfairKing/feedback/blob/d5aa8286fe5913baad0555998e0d60313fdf0db8/feedback/src/Feedback/Loop/Filter.hs#L65-L72

This just freezes on Windows: the process for `git ls-files` runs, but does not return control to `feedback`. If I replace this function with `readProcess`, things work as expected. I must admit that I know absolutely nothing about `process` or `typed-process`, so I have zero clues. @NorfairKing do you have any ideas what could have possibly went wrong?

**Comment by NorfairKing** [comment]
> @NorfairKing do you have any ideas what could have possibly went wrong?

No, but I'm happy to use `process` instead of `typed-process` if that would help ...

**Comment by Bodigrim** [comment]
I guess there must be some secret sauce to make `waitExitCode` work on Windows. Once #7 is merged, I'll ask in `typed-process` bug tracker.
